# Generated by Django 4.2 on 2024-03-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="first name"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=20, verbose_name="middle name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="last name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "М"), ("Female", "Ж")],
                        max_length=6,
                        verbose_name="gender",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="registration date"
                    ),
                ),
                ("user_comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "clothing_size",
                    models.CharField(
                        choices=[
                            ("XS", "Xs"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "Xl"),
                        ],
                        max_length=5,
                        verbose_name="clothing size",
                    ),
                ),
                ("shoe_size", models.CharField(max_length=5, verbose_name="shoe size")),
                (
                    "telegram_link",
                    models.URLField(
                        max_length=50, unique=True, verbose_name="telegram link"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="mobile phone"
                    ),
                ),
                ("blog_link", models.URLField(unique=True, verbose_name="blog link")),
                ("education", models.TextField(verbose_name="education")),
                ("work_place", models.TextField(verbose_name="work place")),
                (
                    "education_target",
                    models.TextField(
                        choices=[
                            (
                                "New profession",
                                "Получение новой профессии, чтобы сменить работу",
                            ),
                            (
                                "Deepen knowledge",
                                "Углубление имеющихся знаний, чтобы использовать их в текущей работе",
                            ),
                            ("Other", "Свой вариант"),
                        ],
                        verbose_name="education target",
                    ),
                ),
                (
                    "education_target_own",
                    models.TextField(
                        blank=True, verbose_name="own target of education"
                    ),
                ),
                (
                    "onboarding_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="onboarding date"
                    ),
                ),
                (
                    "guide_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date of completion of guide",
                    ),
                ),
                (
                    "comment_ambassador",
                    models.TextField(blank=True, verbose_name="ambassador's comment"),
                ),
            ],
            options={
                "verbose_name": "ambassador",
                "verbose_name_plural": "ambassadors",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "program",
                "verbose_name_plural": "programs",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "target",
                "verbose_name_plural": "targets",
            },
        ),
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=20, verbose_name="promocode value"),
                ),
                (
                    "replaced_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="replacement date"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="current"),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocodes",
                        to="ambassadors.ambassador",
                        verbose_name="ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "promocode",
                "verbose_name_plural": "promocodes",
            },
        ),
        migrations.AddField(
            model_name="ambassador",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.program",
                verbose_name="program",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.status",
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="targets",
            field=models.ManyToManyField(
                related_name="ambassadors",
                to="ambassadors.target",
                verbose_name="targets",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=20, verbose_name="country")),
                ("city", models.CharField(max_length=20, verbose_name="city")),
                ("address", models.CharField(max_length=100, verbose_name="address")),
                ("code", models.CharField(max_length=10, verbose_name="postal code")),
                (
                    "replaced_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="replacement date"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="current"),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="ambassadors.ambassador",
                        verbose_name="ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
    ]
