# Generated by Django 4.2 on 2024-02-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                ("last_name", models.CharField(max_length=20, verbose_name="Фамилия")),
                ("gender", models.CharField(max_length=5, verbose_name="Пол")),
                (
                    "registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "user_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий пользователся"
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[("ACTIVE", "Активный"), ("INACTIVE", "Неактивный")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Активность",
                    ),
                ),
                (
                    "clothing_size",
                    models.CharField(max_length=5, verbose_name="Размер одежды"),
                ),
                (
                    "shoe_size",
                    models.CharField(max_length=5, verbose_name="Размер обуви"),
                ),
                (
                    "telegram_login",
                    models.CharField(
                        max_length=20, verbose_name="Имя пользователя телеграм"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "mobile_phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("blog_link", models.TextField(verbose_name="Ссылка на блог")),
                ("education", models.TextField(verbose_name="Образование")),
                ("work_place", models.TextField(verbose_name="Место работы")),
                ("education_target", models.TextField(verbose_name="Цель образования")),
                (
                    "onboarding_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата онбординга"
                    ),
                ),
                (
                    "guide_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата прохождения гайда"
                    ),
                ),
                (
                    "comment_ambassador",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий амбассадора"
                    ),
                ),
            ],
            options={
                "verbose_name": "амбассадор",
                "verbose_name_plural": "амбассадоры",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambassador_target",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название программы"
                    ),
                ),
            ],
            options={
                "verbose_name": "программа",
                "verbose_name_plural": "программы",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название статуса"
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название цели"
                    ),
                ),
                (
                    "ambassadors",
                    models.ManyToManyField(
                        related_name="targets",
                        through="ambassadors.AmbassadorTarget",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадоры",
                    ),
                ),
            ],
            options={
                "verbose_name": "цель",
                "verbose_name_plural": "цели",
            },
        ),
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=20, verbose_name="Значение промокода"),
                ),
                (
                    "replaced_at",
                    models.DateField(blank=True, null=True, verbose_name="Дата замены"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Текущий"),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocodes",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "промокод",
                "verbose_name_plural": "промокоды",
            },
        ),
        migrations.AddField(
            model_name="ambassadortarget",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassador_target",
                to="ambassadors.target",
                verbose_name="Цель",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassadors",
                to="ambassadors.program",
                verbose_name="программа",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassadors",
                to="ambassadors.status",
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=20, verbose_name="Страна")),
                ("city", models.CharField(max_length=20, verbose_name="Город")),
                ("address", models.CharField(max_length=50, verbose_name="Адрес")),
                (
                    "code",
                    models.CharField(max_length=10, verbose_name="Почтовый индекс"),
                ),
                (
                    "replaced_at",
                    models.DateField(blank=True, null=True, verbose_name="Дата замены"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Текущий"),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="ambassadors.ambassador",
                        verbose_name="амбассадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ambassadortarget",
            unique_together={("ambassador", "target")},
        ),
    ]
