# Generated by Django 4.2 on 2024-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="blog_link",
            field=models.URLField(unique=True, verbose_name="ссылка на блог"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="clothing_size",
            field=models.CharField(
                choices=[
                    ("XS", "Xs"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "Xl"),
                ],
                max_length=5,
                verbose_name="размер одежды",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="education_target",
            field=models.TextField(
                choices=[
                    (
                        "Получение новой профессии, чтобы сменить работу",
                        "New profession",
                    ),
                    (
                        "Углубление имеющихся знаний, чтобы использовать их в текущей работе",
                        "Deepen knowledge",
                    ),
                    ("Свой вариант", "Other"),
                ],
                verbose_name="цель образования",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="mobile_phone",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="telegram_login",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="имя пользователя телеграм"
            ),
        ),
    ]
