# Generated by Django 4.2 on 2024-03-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_full_name', models.CharField(blank=True, max_length=50)),
                ('incorrect_telegram_link', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('guide_check', models.BooleanField(default=False, help_text='Контент в рамках Гайда начинающего амбассадора')),
                ('status', models.CharField(choices=[], max_length=20, verbose_name='статус')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('user_comment', models.TextField(verbose_name='комментарий')),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='ambassadors.ambassador')),
            ],
            options={
                'verbose_name': 'контент',
                'verbose_name_plural': 'контент',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название социальной сети')),
            ],
            options={
                'verbose_name': 'социальная сеть',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='путь до файла')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_files', to='content.content')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='content.socialnetwork'),
        ),
    ]
