# Generated by Django 4.2 on 2024-03-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name_from_form",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="first name from form",
                    ),
                ),
                (
                    "last_name_from_form",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="last name from form",
                    ),
                ),
                (
                    "telegram_link_from_form",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="telegram link from form",
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="Link to content", verbose_name="link"),
                ),
                (
                    "guide_check",
                    models.BooleanField(
                        default=False,
                        help_text="Content on topic of Beginner's Ambassador Guide",
                        verbose_name="guide check",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новый", "New"),
                            ("Соответствует", "Respond"),
                            ("Не соответствует", "Not Respond"),
                            ("Уточняется", "TBC"),
                        ],
                        default="Новый",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateField(auto_now_add=True, verbose_name="upload date"),
                ),
                ("user_comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "ambassador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contents",
                        to="ambassadors.ambassador",
                        verbose_name="ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "content",
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "social network",
                "verbose_name_plural": "social networks",
            },
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="content_files/", verbose_name="file"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_files",
                        to="content.content",
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "verbose_name": "content file",
                "verbose_name_plural": "content files",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="social_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contents",
                to="content.socialnetwork",
                verbose_name="social_network",
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ambassador__isnull", True),
                        models.Q(("first_name_from_form", ""), _negated=True),
                        models.Q(("last_name_from_form", ""), _negated=True),
                        models.Q(("telegram_link_from_form", ""), _negated=True),
                    ),
                    models.Q(
                        ("ambassador__isnull", False),
                        ("first_name_from_form", ""),
                        ("last_name_from_form", ""),
                        ("telegram_link_from_form", ""),
                    ),
                    _connector="OR",
                ),
                name="fields_named_from_form_and_ambassador_field",
                violation_error_message="Fields named '..._from_form' and 'ambassador' cannot be empty or filled in at the same time.",
            ),
        ),
    ]
