# Generated by Django 4.2 on 2024-03-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorrect_first_name",
                    models.CharField(
                        blank=True,
                        help_text="Incorrect first name from form",
                        max_length=20,
                        verbose_name="incorrect first name",
                    ),
                ),
                (
                    "incorrect_last_name",
                    models.CharField(
                        blank=True,
                        help_text="Incorrect last name from form",
                        max_length=20,
                        verbose_name="incorrect last name",
                    ),
                ),
                (
                    "incorrect_telegram_link",
                    models.CharField(
                        blank=True,
                        help_text="Incorrect telegram link from form",
                        max_length=50,
                        verbose_name="incorrect telegram link",
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="Link to content", verbose_name="link"),
                ),
                (
                    "guide_check",
                    models.BooleanField(
                        default=False,
                        help_text="Content on topic of Beginner's Ambassador Guide",
                        verbose_name="guide check",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "Новый"),
                            ("Respond", "Соответствует"),
                            ("Not respond", "Не соответствует"),
                            ("TBC", "Уточняется"),
                        ],
                        default="New",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="upload date"),
                ),
                ("user_comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "ambassador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contents",
                        to="ambassadors.ambassador",
                        verbose_name="ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "content",
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "social network",
                "verbose_name_plural": "social networks",
            },
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to="content_files/", verbose_name="file"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_files",
                        to="content.content",
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "verbose_name": "content file",
                "verbose_name_plural": "content files",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="social_network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contents",
                to="content.socialnetwork",
                verbose_name="social_network",
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("ambassador__isnull", True),
                        models.Q(("incorrect_first_name", ""), _negated=True),
                        models.Q(("incorrect_last_name", ""), _negated=True),
                        models.Q(("incorrect_telegram_link", ""), _negated=True),
                    ),
                    models.Q(
                        ("ambassador__isnull", False),
                        ("incorrect_first_name", ""),
                        ("incorrect_last_name", ""),
                        ("incorrect_telegram_link", ""),
                    ),
                    _connector="OR",
                ),
                name="fields_for_incorrect_data_and_ambassador_field",
                violation_error_message="Fields for incorrect data and ambassador field cannot be empty or filled at same time.",
            ),
        ),
    ]
