# Generated by Django 4.2 on 2024-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                ("last_name", models.CharField(max_length=20, verbose_name="Фамилия")),
                ("email", models.CharField(max_length=20, verbose_name="Почта")),
                (
                    "registration_date",
                    models.DateField(verbose_name="Дата регистрации"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user/avatars",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("last_name",),
            },
        ),
    ]
