# Generated by Django 4.2 on 2024-02-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.CharField(
                default="default_username",
                max_length=20,
                unique=True,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=20, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20, verbose_name="Пароль пользователя"),
        ),
    ]
