# Generated by Django 4.2 on 2024-02-28 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_login_alter_user_email_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="login",
            new_name="username",
        ),
    ]
