# Generated by Django 4.2 on 2024-02-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_username_alter_user_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("last_name",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="", max_length=150, unique=True, verbose_name="имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=20, unique=True, verbose_name="почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(max_length=20, verbose_name="отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateField(verbose_name="дата регистрации"),
        ),
    ]
