# Generated by Django 4.2 on 2024-03-01 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="наименование"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Shoes", "Shoes"),
                            ("Clothing", "Clothing"),
                            ("Miscellaneous", "Misc"),
                        ],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(verbose_name="цена за единицу"),
                ),
            ],
            options={
                "verbose_name": "мерч",
                "verbose_name_plural": "мерч",
            },
        ),
        migrations.CreateModel(
            name="Sending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(editable=False, verbose_name="UID отправки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("Error", "Error")],
                        default="Sent",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "user_comment",
                    models.TextField(blank=True, verbose_name="комментарий"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sendings",
                        to="ambassadors.address",
                        verbose_name="адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "отправка",
                "verbose_name_plural": "отправки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SendingToMerch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10, verbose_name="размер")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ],
                        verbose_name="количество",
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        help_text="Цена за единицу на момент отправки",
                        verbose_name="цена за единицу",
                    ),
                ),
                (
                    "merch",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sending_to_merches",
                        to="sendings.merch",
                        verbose_name="мерч",
                    ),
                ),
                (
                    "sending",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sending_to_merches",
                        to="sendings.sending",
                        verbose_name="отправка",
                    ),
                ),
            ],
            options={
                "verbose_name": "мерч в отправке",
                "verbose_name_plural": "мерч в отправке",
            },
        ),
        migrations.AddField(
            model_name="sending",
            name="merches",
            field=models.ManyToManyField(
                related_name="sendings",
                through="sendings.SendingToMerch",
                to="sendings.merch",
                verbose_name="мерч",
            ),
        ),
        migrations.AddIndex(
            model_name="sendingtomerch",
            index=models.Index(
                fields=["sending", "merch", "size"], name="sending_merch_size_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sendingtomerch",
            constraint=models.UniqueConstraint(
                fields=("sending", "merch", "size"),
                name="merch_with_size_is_unique_in_sending",
                violation_error_message="Merch with this size must be unique in this sending.",
            ),
        ),
        migrations.AddIndex(
            model_name="sending",
            index=models.Index(fields=["created_at"], name="created_at_idx"),
        ),
    ]
