version: "3.8"

volumes:
  ambassadors_postgres_data:
  ambassadors_static:
  ambassadors_media:

services:
  ambassadors_postgres:
    container_name: ambassadors_postgres
    image: postgres:16.1-alpine
    env_file:
      - ../.env
    restart: on-failure
    volumes:
      - ambassadors_postgres_data:/var/lib/postgresql/data/

  ambassadors_back:
    container_name: ambassadors_back
    image: $DOCKER_REPO_BACK:1.0.0
    env_file:
      - ../.env
    expose:
      - "8008"
    restart: on-failure
    volumes:
      - ambassadors_static:/app/static/
      - ambassadors_media:/app/media/
    depends_on:
      - ambassadors_postgres
    command: ["./wait_database.sh", "./run_app.dev.sh"]

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    env_file:
      - ../.env
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
      - ambassadors_static:/var/html/ambassadors/static/
      - ambassadors_media:/var/html/ambassadors/media/
    depends_on:
      - ambassadors_back
